import { Member, Task, Language, CategoryItem } from '../types';

export const TASK_COLOR_OPTIONS = [
  { name: 'Gyllene Amber', hex: '#f59e0b' },
  { name: 'Smaragdgrön', hex: '#10b981' },
  { name: 'Himmelsblå', hex: '#0ea5e9' },
  { name: 'Rosaröd', hex: '#f43f5e' },
  { name: 'Klar Lila', hex: '#a855f7' },
  { name: 'Indigo', hex: '#6366f1' },
  { name: 'Havs-Teal', hex: '#14b8a6' },
  { name: 'Sol-Orange', hex: '#f97316' },
  { name: 'Hallonrosa', hex: '#ec4899' },
  { name: 'Limegrön', hex: '#84cc16' },
  { name: 'Kungsblå', hex: '#3b82f6' },
  { name: 'Varm Terrakotta', hex: '#d97706' },
];

export const getDefaultCategories = (lang: Language = 'sv'): CategoryItem[] => {
  if (lang === 'ar') {
    return [
      { id: 'kitchen', name: 'المطبخ والصحون', icon: '🍽️', color: '#f59e0b' },
      { id: 'cleaning', name: 'التنظيف والأرضيات', icon: '🧹', color: '#10b981' },
      { id: 'laundry', name: 'الغسيل والملابس', icon: '🧺', color: '#6366f1' },
      { id: 'cooking', name: 'الطبخ والوجبات', icon: '🍳', color: '#f43f5e' },
      { id: 'shopping', name: 'التسوق والبقالة', icon: '🛒', color: '#06b6d4' },
      { id: 'outdoor', name: 'الخارج والنفايات', icon: '🗑️', color: '#84cc16' },
      { id: 'bathroom', name: 'الحمام', icon: '🚿', color: '#3b82f6' },
      { id: 'organization', name: 'الترتيب والتنظيم', icon: '✨', color: '#a855f7' },
      { id: 'pets', name: 'الحيوانات الأليفة', icon: '🐱', color: '#ec4899' },
    ];
  }

  if (lang === 'en') {
    return [
      { id: 'kitchen', name: 'Kitchen & Dishes', icon: '🍽️', color: '#f59e0b' },
      { id: 'cleaning', name: 'Cleaning & Floors', icon: '🧹', color: '#10b981' },
      { id: 'laundry', name: 'Laundry & Clothes', icon: '🧺', color: '#6366f1' },
      { id: 'cooking', name: 'Cooking & Meals', icon: '🍳', color: '#f43f5e' },
      { id: 'shopping', name: 'Groceries & Errands', icon: '🛒', color: '#06b6d4' },
      { id: 'outdoor', name: 'Outdoors & Trash', icon: '🗑️', color: '#84cc16' },
      { id: 'bathroom', name: 'Bathroom', icon: '🚿', color: '#3b82f6' },
      { id: 'organization', name: 'Organizing & Tidy', icon: '✨', color: '#a855f7' },
      { id: 'pets', name: 'Pets', icon: '🐱', color: '#ec4899' },
    ];
  }

  return [
    { id: 'kitchen', name: 'Kök & Disk', icon: '🍽️', color: '#f59e0b' },
    { id: 'cleaning', name: 'Städning & Golv', icon: '🧹', color: '#10b981' },
    { id: 'laundry', name: 'Tvätt & Kläder', icon: '🧺', color: '#6366f1' },
    { id: 'cooking', name: 'Matlagning', icon: '🍳', color: '#f43f5e' },
    { id: 'shopping', name: 'Handling & Inköp', icon: '🛒', color: '#06b6d4' },
    { id: 'outdoor', name: 'Ute & Sopor', icon: '🗑️', color: '#84cc16' },
    { id: 'bathroom', name: 'Badrum', icon: '🚿', color: '#3b82f6' },
    { id: 'organization', name: 'Ordning & Plock', icon: '✨', color: '#a855f7' },
    { id: 'pets', name: 'Husdjur', icon: '🐱', color: '#ec4899' },
  ];
};

export const AVATAR_OPTIONS = [
  '👩‍🦰', '👨‍🦱', '👧', '👦', '👵', '👴', '👱‍♂️', '👱‍♀️',
  '🧑‍🍳', '🦸‍♀️', '🦸‍♂️', '🐱', '🐶', '⭐', '🚀', '👑'
];

export const COLOR_OPTIONS = [
  { name: 'Indigo', hex: '#6366f1', bgLight: 'bg-indigo-50', text: 'text-indigo-700', border: 'border-indigo-200', fill: 'bg-indigo-600' },
  { name: 'Emerald', hex: '#10b981', bgLight: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200', fill: 'bg-emerald-600' },
  { name: 'Amber', hex: '#f59e0b', bgLight: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200', fill: 'bg-amber-500' },
  { name: 'Rose', hex: '#f43f5e', bgLight: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200', fill: 'bg-rose-500' },
  { name: 'Purple', hex: '#a855f7', bgLight: 'bg-purple-50', text: 'text-purple-700', border: 'border-purple-200', fill: 'bg-purple-600' },
  { name: 'Cyan', hex: '#06b6d4', bgLight: 'bg-cyan-50', text: 'text-cyan-700', border: 'border-cyan-200', fill: 'bg-cyan-600' },
  { name: 'Blue', hex: '#3b82f6', bgLight: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200', fill: 'bg-blue-600' },
  { name: 'Teal', hex: '#14b8a6', bgLight: 'bg-teal-50', text: 'text-teal-700', border: 'border-teal-200', fill: 'bg-teal-600' },
];

export const getDefaultMembers = (lang: Language = 'sv'): Member[] => {
  if (lang === 'ar') {
    return [
      {
        id: 'mem_1',
        name: 'مريم (الأم)',
        avatar: '👩‍🦰',
        color: '#6366f1',
        role: 'أم الأسرة',
        ageGroup: 'adult',
        capacityWeight: 1.0,
        availableDays: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 'mem_2',
        name: 'ياسين (الأب)',
        avatar: '👨‍🦱',
        color: '#10b981',
        role: 'رب الأسرة',
        ageGroup: 'adult',
        capacityWeight: 1.0,
        availableDays: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 'mem_3',
        name: 'سامي (الابن)',
        avatar: '👦',
        color: '#f59e0b',
        role: 'الابن الأكبر',
        ageGroup: 'teen',
        capacityWeight: 0.75,
        availableDays: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 'mem_4',
        name: 'نور (الابنة)',
        avatar: '👧',
        color: '#f43f5e',
        role: 'الابنة الصغرى',
        ageGroup: 'child',
        capacityWeight: 0.5,
        availableDays: [0, 2, 4, 5, 6],
      },
    ];
  }

  if (lang === 'en') {
    return [
      {
        id: 'mem_1',
        name: 'Emma (Mom)',
        avatar: '👩‍🦰',
        color: '#6366f1',
        role: 'Mom',
        ageGroup: 'adult',
        capacityWeight: 1.0,
        availableDays: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 'mem_2',
        name: 'Alex (Dad)',
        avatar: '👨‍🦱',
        color: '#10b981',
        role: 'Dad',
        ageGroup: 'adult',
        capacityWeight: 1.0,
        availableDays: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 'mem_3',
        name: 'Lucas (Son)',
        avatar: '👦',
        color: '#f59e0b',
        role: 'Son',
        ageGroup: 'teen',
        capacityWeight: 0.75,
        availableDays: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        id: 'mem_4',
        name: 'Maya (Daughter)',
        avatar: '👧',
        color: '#f43f5e',
        role: 'Daughter',
        ageGroup: 'child',
        capacityWeight: 0.5,
        availableDays: [0, 2, 4, 5, 6],
      },
    ];
  }

  // Default Swedish
  return [
    {
      id: 'mem_1',
      name: 'Anna (Mamma)',
      avatar: '👩‍🦰',
      color: '#6366f1',
      role: 'Mamma',
      ageGroup: 'adult',
      capacityWeight: 1.0,
      availableDays: [0, 1, 2, 3, 4, 5, 6],
    },
    {
      id: 'mem_2',
      name: 'Erik (Pappa)',
      avatar: '👨‍🦱',
      color: '#10b981',
      role: 'Pappa',
      ageGroup: 'adult',
      capacityWeight: 1.0,
      availableDays: [0, 1, 2, 3, 4, 5, 6],
    },
    {
      id: 'mem_3',
      name: 'Liam (Son)',
      avatar: '👦',
      color: '#f59e0b',
      role: 'Son',
      ageGroup: 'teen',
      capacityWeight: 0.75,
      availableDays: [0, 1, 2, 3, 4, 5, 6],
    },
    {
      id: 'mem_4',
      name: 'Ella (Dotter)',
      avatar: '👧',
      color: '#f43f5e',
      role: 'Dotter',
      ageGroup: 'child',
      capacityWeight: 0.5,
      availableDays: [0, 2, 4, 5, 6],
    },
  ];
};

export const getDefaultTasks = (lang: Language = 'sv'): Task[] => {
  if (lang === 'ar') {
    return [
      {
        id: 'tsk_1',
        title: 'تفريغ وتعبئة غسالة الصحون',
        category: 'kitchen',
        color: '#f59e0b',
        points: 2,
        estimatedMinutes: 15,
        frequencyPerWeek: 7,
        icon: '🍽️',
      },
      {
        id: 'tsk_2',
        title: 'إعداد وجبة العشاء',
        category: 'cooking',
        color: '#f43f5e',
        points: 4,
        estimatedMinutes: 45,
        frequencyPerWeek: 5,
        preferredDays: [0, 1, 2, 3, 4],
        requiredAgeGroup: 'adult',
        icon: '🍳',
      },
      {
        id: 'tsk_3',
        title: 'كنس الصالة والممرات بالمكنسة',
        category: 'cleaning',
        color: '#10b981',
        points: 3,
        estimatedMinutes: 25,
        frequencyPerWeek: 3,
        preferredDays: [1, 3, 5],
        icon: '🧹',
      },
      {
        id: 'tsk_4',
        title: 'إخراج كيس القمامة والتدوير',
        category: 'outdoor',
        color: '#84cc16',
        points: 1,
        estimatedMinutes: 5,
        frequencyPerWeek: 4,
        preferredDays: [0, 2, 4, 6],
        icon: '🗑️',
      },
      {
        id: 'tsk_5',
        title: 'غسيل الملابس ونشرها',
        category: 'laundry',
        color: '#6366f1',
        points: 3,
        estimatedMinutes: 30,
        frequencyPerWeek: 3,
        preferredDays: [2, 4, 6],
        icon: '🧺',
      },
      {
        id: 'tsk_6',
        title: 'تنظيف وتعقيم الحمام',
        category: 'bathroom',
        color: '#0ea5e9',
        points: 4,
        estimatedMinutes: 35,
        frequencyPerWeek: 2,
        preferredDays: [2, 5],
        icon: '🚿',
      },
      {
        id: 'tsk_7',
        title: 'شراء حاجيات البقالة الأسبوعية',
        category: 'shopping',
        color: '#14b8a6',
        points: 4,
        estimatedMinutes: 60,
        frequencyPerWeek: 2,
        preferredDays: [1, 5],
        requiredAgeGroup: 'adult',
        icon: '🛒',
      },
      {
        id: 'tsk_8',
        title: 'ترتيب طاولة الطعام ومسحها',
        category: 'organization',
        color: '#a855f7',
        points: 1,
        estimatedMinutes: 10,
        frequencyPerWeek: 7,
        icon: '✨',
      },
      {
        id: 'tsk_9',
        title: 'سقي نباتات المنزل',
        category: 'outdoor',
        color: '#10b981',
        points: 1,
        estimatedMinutes: 10,
        frequencyPerWeek: 2,
        preferredDays: [2, 6],
        icon: '🪴',
      },
      {
        id: 'tsk_10',
        title: 'مسح وتلميع أرضيات المنزل',
        category: 'cleaning',
        color: '#f97316',
        points: 4,
        estimatedMinutes: 40,
        frequencyPerWeek: 1,
        preferredDays: [5], // Friday
        icon: '🧽',
      },
    ];
  }

  if (lang === 'en') {
    return [
      {
        id: 'tsk_1',
        title: 'Empty & Load Dishwasher',
        category: 'kitchen',
        color: '#f59e0b',
        points: 2,
        estimatedMinutes: 15,
        frequencyPerWeek: 7,
        icon: '🍽️',
      },
      {
        id: 'tsk_2',
        title: 'Cook Dinner',
        category: 'cooking',
        color: '#f43f5e',
        points: 4,
        estimatedMinutes: 45,
        frequencyPerWeek: 5,
        preferredDays: [0, 1, 2, 3, 4],
        requiredAgeGroup: 'adult',
        icon: '🍳',
      },
      {
        id: 'tsk_3',
        title: 'Vacuum Living Room & Hall',
        category: 'cleaning',
        color: '#10b981',
        points: 3,
        estimatedMinutes: 25,
        frequencyPerWeek: 3,
        preferredDays: [1, 3, 5],
        icon: '🧹',
      },
      {
        id: 'tsk_4',
        title: 'Take out Garbage & Recycling',
        category: 'outdoor',
        color: '#84cc16',
        points: 1,
        estimatedMinutes: 5,
        frequencyPerWeek: 4,
        preferredDays: [0, 2, 4, 6],
        icon: '🗑️',
      },
      {
        id: 'tsk_5',
        title: 'Do Laundry & Hang Clothes',
        category: 'laundry',
        color: '#6366f1',
        points: 3,
        estimatedMinutes: 30,
        frequencyPerWeek: 3,
        preferredDays: [2, 4, 6],
        icon: '🧺',
      },
      {
        id: 'tsk_6',
        title: 'Deep Clean Bathroom',
        category: 'bathroom',
        color: '#0ea5e9',
        points: 4,
        estimatedMinutes: 35,
        frequencyPerWeek: 2,
        preferredDays: [2, 5],
        icon: '🚿',
      },
      {
        id: 'tsk_7',
        title: 'Weekly Grocery Shopping',
        category: 'shopping',
        color: '#14b8a6',
        points: 4,
        estimatedMinutes: 60,
        frequencyPerWeek: 2,
        preferredDays: [1, 5],
        requiredAgeGroup: 'adult',
        icon: '🛒',
      },
      {
        id: 'tsk_8',
        title: 'Wipe & Clear Dining Table',
        category: 'organization',
        color: '#a855f7',
        points: 1,
        estimatedMinutes: 10,
        frequencyPerWeek: 7,
        icon: '✨',
      },
      {
        id: 'tsk_9',
        title: 'Water Houseplants',
        category: 'outdoor',
        color: '#10b981',
        points: 1,
        estimatedMinutes: 10,
        frequencyPerWeek: 2,
        preferredDays: [2, 6],
        icon: '🪴',
      },
      {
        id: 'tsk_10',
        title: 'Mop Floors',
        category: 'cleaning',
        color: '#f97316',
        points: 4,
        estimatedMinutes: 40,
        frequencyPerWeek: 1,
        preferredDays: [5], // Saturday
        icon: '🧽',
      },
    ];
  }

  // Default Swedish
  return [
    {
      id: 'tsk_1',
      title: 'Plocka i / ur diskmaskinen',
      description: 'Tömma ren disk och ställa in smutsig disk efter måltider',
      category: 'kitchen',
      color: '#f59e0b',
      points: 2,
      estimatedMinutes: 15,
      frequencyPerWeek: 7,
      icon: '🍽️',
    },
    {
      id: 'tsk_2',
      title: 'Laga middag',
      description: 'Förbereda och tillaga kvällens måltid',
      category: 'cooking',
      color: '#f43f5e',
      points: 4,
      estimatedMinutes: 45,
      frequencyPerWeek: 5,
      preferredDays: [0, 1, 2, 3, 4],
      requiredAgeGroup: 'adult',
      icon: '🍳',
    },
    {
      id: 'tsk_3',
      title: 'Dammsuga vardagsrum & hall',
      description: 'Kör över golv och mattor i gemensamma ytor',
      category: 'cleaning',
      color: '#10b981',
      points: 3,
      estimatedMinutes: 25,
      frequencyPerWeek: 3,
      preferredDays: [1, 3, 5],
      icon: '🧹',
    },
    {
      id: 'tsk_4',
      title: 'Gå ut med sopor & källsortering',
      description: 'Tömma restavfall, matavfall och papper till miljöstugan',
      category: 'outdoor',
      color: '#84cc16',
      points: 1,
      estimatedMinutes: 5,
      frequencyPerWeek: 4,
      preferredDays: [0, 2, 4, 6],
      icon: '🗑️',
    },
    {
      id: 'tsk_5',
      title: 'Tvätta en maskin & hänga tvätt',
      description: 'Sätta igång tvättmaskin och hänga upp på torkställning',
      category: 'laundry',
      color: '#6366f1',
      points: 3,
      estimatedMinutes: 30,
      frequencyPerWeek: 3,
      preferredDays: [2, 4, 6],
      icon: '🧺',
    },
    {
      id: 'tsk_6',
      title: 'Städa badrum & toalett',
      description: 'Rengöra handfat, toalettstol och spegel',
      category: 'bathroom',
      color: '#0ea5e9',
      points: 4,
      estimatedMinutes: 35,
      frequencyPerWeek: 2,
      preferredDays: [2, 5],
      icon: '🚿',
    },
    {
      id: 'tsk_7',
      title: 'Veckohandla mat',
      description: 'Åka till matbutiken och handla enligt inköpslistan',
      category: 'shopping',
      color: '#14b8a6',
      points: 4,
      estimatedMinutes: 60,
      frequencyPerWeek: 2,
      preferredDays: [1, 5],
      requiredAgeGroup: 'adult',
      icon: '🛒',
    },
    {
      id: 'tsk_8',
      title: 'Torka matbordet & duka av',
      description: 'Torka rent bord och köksbänk efter kvällsmat',
      category: 'organization',
      color: '#a855f7',
      points: 1,
      estimatedMinutes: 10,
      frequencyPerWeek: 7,
      icon: '✨',
    },
    {
      id: 'tsk_9',
      title: 'Vattna blommor & krukväxter',
      description: 'Se över alla växter och ge vatten',
      category: 'outdoor',
      color: '#10b981',
      points: 1,
      estimatedMinutes: 10,
      frequencyPerWeek: 2,
      preferredDays: [2, 6],
      icon: '🪴',
    },
    {
      id: 'tsk_10',
      title: 'Våttorka golven',
      description: 'Moppa golven i kök och hall',
      category: 'cleaning',
      color: '#f97316',
      points: 4,
      estimatedMinutes: 40,
      frequencyPerWeek: 1,
      preferredDays: [5], // Lördag
      icon: '🧽',
    },
  ];
};
